<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <?php
    echo $this->headTitle();
    echo $this->headScript();

    $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.min.css');
    echo $this->headLink();
    ?>
    <!-- HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/styles.css" rel="stylesheet" />
  </head>
  
  <body>
    <!-- Topbar
    ================================================== -->
      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <a class="brand" href="/">IMH Status</a>
          <?php $username = App_Service_User::Singleton()->getUsername(); ?>
          <?php if($username): ?>
          <ul class="nav">
          <li><a class "btn btn-inverse" href="/admin/create">Create</a></li>
          </ul>
              <a class="btn btn-inverse pull-right" href="/index/logout">Logout</a>
                <p class="pull-right navbar-text">Logged in as: <?= $username; ?></p>
          <?php else: ?>
          <?php
              $form = new Form_LoginForm();
              echo $form;
              endif;
          ?>
        </div>
      </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <?= $this->navigation()->menu()->setUlClass('nav nav-list'); ?>            
          </div>
        </div>

        <div class="span9">
        <?= $this->layout()->content; ?>
        </div>

      <footer>
        <p>&copy; Joseph Pond 2012</p> 
      </footer>

    </div> <!-- /container-fluid -->


  </body>
</html>
