<?php if ($this->pageCount): ?>
<div class="pagination pagination-centered">
  <ul>
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li>
    <a href="<?= $this->url(array('pageid' => $page), '/page'); ?>">
        <?= $page; ?>
    </a> 
  <?php else: ?>
    <li class="disabled">
    <a href="#">
    <?= $page; ?> 
    </a>
  <?php endif; ?>
    </li>
<?php endforeach; ?>
  </ul>
</div>
<?php endif; ?>
